### ISSUE TITLE
@zeit/Now - Github Integration - Not showing details section

### ISSUE THREAD

**Issue by prajwal88** [zeit/now-github-starter#412]
@zeit/Now - Github Integration - Not showing details section. please find the issue posted on StackOverflow. 

Link---->https://stackoverflow.com/questions/55708311/zeit-now-github-integration-not-working-deployment-queued

**Comment by fybrtech** [comment]
Is this being looked into? I am facing the same issue.

**Comment by supreetpal** [comment]
Is this being looked into? I am facing the same issue?

**Comment by prawn-cake** [comment]
Same issue

**Comment by paulogdm** [comment]
Hello!
Can anybody elaborate a little bit? Any links for us?

**Comment by prawn-cake** [comment]
Hi @paulogdm 
Thanks for the reply!

The link in the description to stackoverflow describes the issue.

I can describe the steps I did to reproduce the issue (or may be it's not and I overlooked something).

I followed the starter project guide, singed up, added gh app, cloned the repo and created a [PR](https://github.com/prawn-cake/now-github-starter/pull/3).
I got email notification that my PR was deployed and the comment from the bot

> This pull request is automatically deployed with Now.
To access deployments, click Details below or on the icon next to each push.

But I can't see the "Details", since that [checks link](https://zeit.co/docs/v2/integrations/now-for-github) is not visible in my PR

**Comment by paulogdm** [comment]
Maybe the `now.json` validation is failing. Can you add `"version": 2` and let me know?

**Comment by supreetpal** [comment]
@paulogdm I tried that. It still doesn't work for me. https://github.com/fybrtech/now-github-starter/pull/1

**Comment by paulogdm** [comment]
My question is, where did you get into this repo?
Did you accessed https://zeit.co/new ?

**Comment by supreetpal** [comment]
When we click "start with github" on the website. https://zeit.co/github
It leads us to here.

**Comment by prawn-cake** [comment]
and now it returns HTTP 500
<img width="830" alt="Screen Shot 2019-05-27 at 16 34 41" src="https://user-images.githubusercontent.com/5894089/58423282-5f622880-809d-11e9-946b-e608afee23e8.png">

**Comment by paulogdm** [comment]
@prawn-cake That is certainly unexpected. Can you give me your user in our platform?

**Comment by prawn-cake** [comment]
I logged in with my github.
Check "prawn-cake" or "ekimovskymaksim"

**Comment by paulogdm** [comment]
I couldn't reproduce... Can you check the console of your browser for hints?

**Comment by prawn-cake** [comment]
Works ok after login, so I probably wasn't authenticated, not sure

**Comment by paulogdm** [comment]
Could not reproduce without login either... Really strange.

**Comment by paulogdm** [comment]
I think this is collateral of disabled deployments for forks. If you create a new repository this will not happen again.
I suggest going to https://zeit.co/new and trying a new repo.
